### PR TITLE
sort item upgrades by dps

### PR DESCRIPTION
**Pull request by paradigm72**
Enhancement: makes the item list displayed when "Suggest upgrades" is selected sorted by their DPS delta from the equipped item, instead of by their initial position in the .hpp file.

### CODE REVIEW

**Comment by paradigm72** [comment]
Ah shoot, I see this is going to conflict with the vigo2's branch, because of the refactor of the upgrades display code. Unless you wanted this sooner, I can just rewrite this change after that PR is merged.

**Comment by TheGroxEmpire** [comment]
> Ah shoot, I see this is going to conflict with the vigo2's branch, because of the refactor of the upgrades display code. Unless you wanted this sooner, I can just rewrite this change after that PR is merged.

Vigo's PR will be the priority atm. You could rewrite it after it has been merged, thank you!

**Comment by vigo2** [comment]
I've included this into cleanup, so you don't have re-read all the refactored code ;) This helped me to uncover a subtle bug, so it paid off already.

**Comment by paradigm72** [comment]
Ok, nice! I see the updates in that branch and that looks like it will work. Exciting changes in there :). Closing this PR.

**Pull request closed without merging**
