### PR TITLE
Add Chain of Unleashed Rage

### LINKED ISSUE #93: Add Chain of Unleashed Rage (P4 badge belt)
Was hoping [Chain of Unleashed Rage](https://tbc.wowhead.com/item=33331/chain-of-unleashed-rage) could be added so the no 100 Deaths gang can see whether it's an upgrade on Red Belt of Battle.

### PR DESCRIPTION
**Pull request by loliver**
[Chain of Unleashed Rage](https://tbc.wowhead.com/item=33331/chain-of-unleashed-rage)
Phase 4 Badge of Justice belt

Unsure whether there's any extra data that needs to be updated, I'm just a web dev hack :)

Fixes #93

### CODE REVIEW

**Comment by TheGroxEmpire** [comment]
@loliver yeah, you need to include it on the index.html and compile the WASM.

**Comment by TheGroxEmpire** [comment]
If you can't do that, I can make it for you.

**Comment by loliver** [comment]
I'll give it a go, doesn't sound too complex.

**Comment by loliver** [comment]
Wasn't counting on setting up a dev environment on Windows 11 being so laborious, would be great if you can do the WASM build.

**Comment by TheGroxEmpire** [comment]
Thanks for making the PR. It's merged now.

**Pull request merged**
