### PR TITLE
feat: sim slamming with 1 handers too

### PR DESCRIPTION
**Pull request by k13gomez**
I wanted to be able to simulate Slam with DW Arms, this allows slamming without caring about 2h/1h.

### CODE REVIEW

**Review by TheGroxEmpire — CHANGES_REQUESTED** [review]
Currently as it stands, the slam casting system doesn't reset OH swing timer.
```
Time: 6.921780s. Event: Starting to cast slam. Latency: 0.100000s
Time: 8.521790s. Event: Slam!
Time: 8.521790s. Event: Drawing outcome from yellow (mh)
Time: 8.521790s. Event: Ability hit for: 741 damage.
Time: 8.521790s. Event: Current rage: 25
Time: 8.521790s. Event: Drawing outcome from white (oh)
```
To enable slamming for dual-wield, we'd have to change how slam casting works. It needs to reset the swing time for both MH and OH. The slam function that needs to be modified is in Combat_simulator.cpp: 437.

**Comment by vigo2** [comment]
The "slam is casting" code is right before regular swings are handled, in Combat_simulator.cpp:1208. It should suffice to add a reset for the OH as well:

```
if (slam_manager.is_slam_casting())
{
    if (!slam_manager.ready(time_keeper_.time))
    {
        continue;  // the swing timer is effectively stopped while slam is casting
    }

    slam(weapons[0], special_stats, damage_sources, flurry_charges, rampage_stacks);
    slam_manager.finish_slam();
    
    // reset MH
    weapons[0].next_swing = time_keeper_.time + weapons[0].swing_speed / (1 + special_stats.haste);

    // ... and now OH as well
    if (is_dual_wield)
    {
        weapons[1].next_swing = time_keeper_.time + weapons[1].swing_speed / (1 + special_stats.haste);
    }

    oldHaste = state.special_stats.haste; // keep update_swing_timer() from applying haste changes again
}

```

**Comment by k13gomez** [comment]
Yeah I made those changes and I think it looks good now, pushing changes soon:
```
Time: 8.717259s. Event: Starting to cast slam. Latency: 0.000000s
Time: 9.000010s. Event: Over time effect: anger_management tick. Current rage: 100
Time: 9.217269s. Event: Slam!
Time: 9.217269s. Event: Drawing outcome from yellow (mh)
Time: 9.217269s. Event: Ability crit for: 2029 damage.
Time: 9.217269s. Event: Current rage: 85
Time: 9.217269s. Event: Heroic strike activated
Time: 9.500020s. Event: Current rage: 95
Time: 10.500030s. Event: Over time effect: Bloodrage tick. Current rage: 96
Time: 10.905108s. Event: Performing Heroic Strike
Time: 10.905108s. Event: Drawing outcome from yellow (mh)
Time: 10.905108s. Event: Ability hit for: 927 damage.
Time: 10.905108s. Event: Unbridled wrath. Current rage: 85
Time: 10.905108s. Event: Current rage: 85
Time: 10.905108s. Event: Drawing outcome from white (oh)
```

**Review by TheGroxEmpire — APPROVED** [review]
LGTM!

**Pull request merged**
